# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Run tests

on:
  push:
    branches: [ master, feature/*, fix/*, refactor/*, chore/*, release/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint
      run: |
        echo "lint"
    - name: Test
      run: |
        echo "test"
