# This workflow runs the regression test to make sure that
# the model training is effective. More specifically, it
# requires the model to outperform the random policy after
# a certain number of iterations.

name: Regression Tests
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */6 * * *'
  pull_request:
    branches: 
      - master
jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Regression tests
      run: |
        python -m unittest \
          train_test.TestTrain.test_training_effectiveness
